{% set version = "1.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set cran_mirror = "https://cran.r-project.org" %}

package:
  name: r-subplex
  version: {{ version|replace("-", "_") }}

source:
  fn: subplex_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/subplex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/subplex/subplex_{{ version }}.tar.gz
  sha256: 0d05da1622fffcd20a01cc929fc6c2b7df40a8246e7018f7f1f3c175b774cbf9

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('subplex')"           # [not win]
    - "\"%R%\" -e \"library('subplex')\""  # [win]

about:
  home: https://github.com/kingaa/subplex/
  license: GPL-3
  summary: The subplex algorithm for unconstrained optimization, developed by Tom Rowan <http://www.netlib.org/opt/subplex.tgz>.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3  # [unix]
  license_file: {{ environ["PREFIX"] }}\R\share\licenses\GPL-3  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
