travis:
  secure:
    BINSTAR_TOKEN: EXqkK6yGgCFm/qaxUvh6+wYhW5z8tHsXngDVEexQMmzEtpIpHnkhcDSSWU+VHEWBW7UA5kLli90Udjk28mDhQFmIWbu7FbNIYfj7RgvLGlPq4O6ouDvU9fgvWk/grB3kesfwJm6r5uHbOuTMjpKWPhfnWV+f1hPzgaWMaVbWbvMaFBEuqsNE16tLHOkqMM8x4O0nVp0KtR/tPOQ0C66rkKbLBiRpWAVjVvcIlPOZMzJeq5ymOXksnyYLTfd2KSb8g5pFNAvAf2oeOHd/NJjEAE8jQpvIRsk665TPbtMTG0TcROdrGyDKWJwo7c/2v4ZNuwtv/gqH34OQD/r5lvr8LjvIOJyiURL+wV8/TgnG9eTE3ZfWxmOawYYIGgUHYcMrn0cQEX39polUPF1YzsdINKfDb/xAEcCFEOOrTCKZ0u6Y267OZyQOi7xJoAGFS5yJU9hYIvTSyV3nwj0AKIT8BlTqqVjPKI4C2QjxRl3hGeLP5VWkqvhKpm7h0iww05rBvGlUl0ntnOzTtj0JBZgCA/gydTp1+4pv3oYyaJ603Zq7e6K+9S9jaLwGjbHrB4G0C3CYYk+PPolt26NssoV35SNTR5jL+wjIQsaN5tKhmmUI/jtHczxozLpKzFxw5eoSi7rcbxKprT4QAb2G4bnXpAHnySfHKoWHWDC2Njhq+io=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
