appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: uFol8utjs4M9S98YjemfQ980L4dKbW+F+UtoTcMv+Ch3dXnbKKNI56kDcxUa8a2HK4N2rrwQNn7AbTMfJVvcxvIBJIeQcX8NnwvD49uMTUdm+jG/LFNWMD/AxG0nRTKb4lw01PuXHPj68IvCPoGfkPapwMTF27IRqyFXooJpB0gybcEg/iXVNdHDSbQclrGHhKBit6B44YSr8575pQgZzgUW6zc+LZfxrv76EMU4NxyygIGgp4pjYD/R/8HKvPDw7HwLDcOpBEOjgsoKVjHmkMCQC7cDY7Pra/kBvTboiDJHM02LdZYzaGxUvpdX91RRVkY4KnGmdM60opocZz24espt9aRJ2P/5t4wketi8XDMevmPrBoC9sUcHqkYH0Gbbs58lrJj5xzsJ3ZmpC9J2LomgN5fmIlkO0+r9E+c1Lgv2V5bsFnLG+T6oH9K6L15WPDqKPx7TikznnGCaC6g9TLJPmpjjfOIq1p56BbSXiBWbq8ZbW+uhPwIHFj9AOKhRcls1JdjZJ9yP+POLUx6qC4H2JGg7gCMoUtxDArF2lYGf9NsnAu+1DPge5fpnDDoI7Seof0KoM9fmgW484OCj2NOejhAbhODS0M/HgRH/mEcT0NVck8/ggqPCMoO+WgZcquPA7p4Ju4knp3sbGC0PVosPOdCUv0lS281Lazc3eYc=}
